# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luna Gao - 猫咪神
email: gao.xue.qi@qq.com
power_by: power by Jekyll & Bootstrap
description: >
  LunaGao, maomishen
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lunagao.github.io" # the base hostname & protocol for your site
weibo_username: maomishen
github_username:  LunaGao

# Pagination
gems: [jekyll-paginate, rouge]
paginate: 2
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
